name: CD Pipeline

on: 
  push:
    branches:
      - main # Runs on pushes to the main branch

jobs:
  deploy:
    runs_on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: 
