name: CI Pipeline

on:
  pull_request:
    branches:
      - main # Runs on PRs to the main branch

jobs:
  tests:
    runs-on: ubuntu-latest # Runs on latest ubuntu environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 #pulls the repository code

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
