name: CD Pipeline

on: 
  push:
    branches:
      - main  # Trigger this workflow when there is a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/cli | bash

      - name: Login to Railway CLI
        run: |
          echo "${{ secrets.RAILWAY_TOKEN }}" | railway login

      - name: Deploy to Railway
        run: railway up
