name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # The pipeline runs for pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Using an Ubuntu environment for running tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code in the pull request

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the correct Python version for your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install the dependencies listed in requirements.txt

      - name: Run tests with pytest
        run: |
          pytest  # Run pytest to execute the tests in your project
