name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Starting deployment..."
      
            # Ensure the repository exists
            mkdir -p ~/HNGX-STG2-TASK && cd ~/HNGX-STG2-TASK
      
            # Stop existing containers if running
            echo "Stopping existing containers..."
            docker stop fastapi_app || true
            docker stop nginx_proxy || true
            docker rm fastapi_app || true
            docker rm nginx_proxy || true
      
            # Pull latest code
            echo "Pulling latest changes..."
            git fetch --all
            git reset --hard origin/main
      
            # Build & restart containers
            echo "Building and restarting containers..."
            docker-compose down
            docker-compose up --build -d
            echo "Deployment completed successfully!"
