name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Railway CLI
        run: |
          curl -sSL https://railway.app/cli | bash
          railway login --token ${{ secrets.RAILWAY_API_KEY }}

      - name: Deploy to Railway
        run: railway up --yes
