name: Deploy to Railway

on:
  push:
    branches:
      - main  # The workflow will run when a commit is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Using an Ubuntu environment for deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Install Railway CLI
        run: |
          npm install -g @railway/cli  # Install Railway CLI using npm

      - name: Set Railway API Key
        run: echo ${{ secrets.RAILWAY_API_KEY }} > ~/.railway  # Directly set the API key for Railway CLI

      - name: Deploy to Railway
        run: railway up -- --yes  # Deploy the app to Railway with '--yes' passed correctly
