name: Deploy to Railway

on:
  push:
    branches:
      - main  # The workflow will run when a commit is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Using an Ubuntu environment for deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up Railway CLI
        run: |
          curl -sSL https://railway.app/cli -o railway-cli.sh
          if ! grep -q '#!/bin/bash' railway-cli.sh; then
            echo "Failed to download Railway CLI"
            cat railway-cli.sh  # Output the unexpected content for debugging
            exit 1
          fi
          bash railway-cli.sh
          railway login --token ${{ secrets.RAILWAY_API_KEY }}  # Log in to Railway using the API key

      - name: Deploy to Railway
        run: railway up --yes  # Deploy the app to Railway
